eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp_projects?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update


  config:
    import: optional:configserver:http://localhost:9093

management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
